bgColor1 = '#706145'
bgColor2 = '#523626'
levels = ['Fire']

[sprites.i]
name = 'yaq'
color = '#ffff00'
isPlayer = true
canMove = true
display = '☻'
foods = 's'
freinds = 'r'
forbbiden = 'wt'

[sprites.s]
name = 'star'
group = 'stars'
color = '#ffff00'
display = '★'