hint = 'We can move in all 8 directions'
code = """
left 5
right 10
left 5

up 5
down 10
up 5

upLeft 5
downRight 10
upLeft 5

downLeft 5
upRight 1
"""
answer = """
left 5
right 10
left 5

up 5
down 10
up 5

upLeft 5
downRight 10
upLeft 5

downLeft 5
upRight 10
"""
successMsg = 'Wonderful, you got it!'
layout = """
wwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwww
wwwwwswwwtstwwwswwwwwwww
wwwwww wwt tww wwwwwwwww
wwwwwww wt tw wwwwwwwwww
wwwwwwww     wwwwwwwwwww
wwwwwttt     tttwwwwwwww
wwwwws    i    swwwwwwww
wwwwwttt     tttwwwwwwww
wwwwwwww     wwwwwwwwwww
wwwwwww wt tw wwwwwwwwww
wwwwww wwt tww wwwwwwwww
wwwwwswwwtstwwwswwwwwwww
wwwwwwwwwwwwwwwwwwwwwwww
wwwttwwwwwwwwwwwwwwwwwww
wwwttwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwww
"""