hint = 'You can also draw with upRight, upLeft, downRight, downLeft commands'
code = """
upRight 6
downRight 6
downLeft 6
upLeft 3
"""
answer = """
upRight 6
downRight 6
downLeft 6
upLeft 5
"""
successMsg = 'well done!'
layout = """



         x
        x x
       x   x
      x     x
     x       x
    x         x
   P           x
    x         x
     x       x
      x     x
       x   x
        x x
         x
"""
