name = 'Turtle graphics'
mode = "turtle"
rows = 20
columns = 20
levels = ['rectangle', 'diamond', 'house']
[sprites.p]
isPen = true
[sprites.p.pen]
display = '◉'
color = '#cccc00'
[sprites.x.block]
bgColor = '#555555'
[sprites.P]
sprites = 'xp'
