hint = 'Use up, down, left, right commands to draw'
code = """
right 6
down 6
left 6
up 3
"""
answer = """
right 6
down 6
left 6
up 5
"""
successMsg = 'good job!'
layout = """






      Pxxxxxx
      x     x
      x     x
      x     x
      x     x
      x     x
      xxxxxxx
"""
